#!/bin/csh -f

set cell_name   = HEADTIESQ_DX_N_S6P25TR_C54L06
set temperature = 25
set voltage     = 0.5500
set process     = TT
set switch_pin  = SLEEP
set spice_file  = ./db/HEADTIESQ_DX_N_S6P25TR_C54L06.spf
set workspace   = ./ws

set REDHAWK_HOME = /eda-tools/apache/RedHawk_Linux64e6_V19.1.4/bin
set LISENCE_FILE = /eda-tools/env/ansys.csh.any
set hspice_path  = /eda-tools/synopsys/hspice_vQ-2020.03-SP2-1/hspice/Q-2020.03-SP2-1/hspice/bin/hspice
# spice 引用的库
set spice_lib    = /ic-library/samsung/ln04lpp/pdk/LN04LPP_HSPICE_S00-V1.0.6.0/HSPICE/LN04LPP_Hspice.lib
